### ISSUE TITLE
After update to 2021.4.1, miele integration gives errors at start and while running

### ISSUE THREAD

**Issue by FransHalsjes** [HomeAssistant-Mods/home-assistant-miele#38]
Error during startup:

```
Logger: homeassistant.bootstrap
Source: bootstrap.py:392
First occurred: 13:27:51 (1 occurrences)
Last logged: 13:27:51

Waiting on integrations to complete setup: miele
```
and
```
Logger: homeassistant.bootstrap
Source: bootstrap.py:392
First occurred: 13:27:51 (1 occurrences)
Last logged: 13:27:51

Waiting on integrations to complete setup: miele
````

Error during runtime:

```
Logger: homeassistant
Source: helpers/entity.py:455
First occurred: 13:29:14 (62 occurrences)
Last logged: 13:33:45

Error doing job: Task exception was never retrieved
Traceback (most recent call last):
  File "/config/custom_components/miele/__init__.py", line 174, in refresh_devices
    platform.update_device_state()
  File "/config/custom_components/miele/binary_sensor.py", line 49, in update_device_state
    device.async_schedule_update_ha_state(True)
  File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 455, in async_schedule_update_ha_state
    self.hass.async_create_task(self.async_update_ha_state(force_refresh))
AttributeError: 'NoneType' object has no attribute 'async_create_task'
```

**Comment by marconfus** [comment]
Looks like the "AssertionError" became an "AttributeError" in HA as the exception is only thrown for "devices" that I have manually disabled.

**Comment by kloknibor** [comment]
@marconfus what type of devices did you hide? We had this error before and I think I fixed it on all devices but might have missed some.

**Comment by marconfus** [comment]
I disabled the irrelevant temperature sensors like "sensor.washing_machine_target_temperature_1" or "sensor.freezer_temperature_2". After adding some debug code I saw the exception is raised only for these device objects.

**Comment by kloknibor** [comment]
@marconfus allright I'll take a look this week, thanks!

**Comment by mhaack** [comment]
+1 get the same error after #39 was fixed.

**Comment by kloknibor** [comment]
Should be solved after next Dev to Master PR :-)! Please let me know if not the case.
